// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcuw8cC_E5bB97IR-t-l_4lpqFOzTJg94',
    appId: '1:305063137344:web:36ed38ab748b2d0a18cfa5',
    messagingSenderId: '305063137344',
    projectId: 'coffee-house-jamee',
    authDomain: 'coffee-house-jamee.firebaseapp.com',
    storageBucket: 'coffee-house-jamee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVtP2LkaGOC3kSDBTam1RxSZjjQRZFdYY',
    appId: '1:305063137344:android:cc3a5af466f65ceb18cfa5',
    messagingSenderId: '305063137344',
    projectId: 'coffee-house-jamee',
    storageBucket: 'coffee-house-jamee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzluVRD9grmnms--XRjhxkJlYB9pSTWxg',
    appId: '1:305063137344:ios:58c922f212c6315118cfa5',
    messagingSenderId: '305063137344',
    projectId: 'coffee-house-jamee',
    storageBucket: 'coffee-house-jamee.firebasestorage.app',
    iosBundleId: 'com.example.summerIubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzluVRD9grmnms--XRjhxkJlYB9pSTWxg',
    appId: '1:305063137344:ios:58c922f212c6315118cfa5',
    messagingSenderId: '305063137344',
    projectId: 'coffee-house-jamee',
    storageBucket: 'coffee-house-jamee.firebasestorage.app',
    iosBundleId: 'com.example.summerIubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcuw8cC_E5bB97IR-t-l_4lpqFOzTJg94',
    appId: '1:305063137344:web:6b8314f20cf30da018cfa5',
    messagingSenderId: '305063137344',
    projectId: 'coffee-house-jamee',
    authDomain: 'coffee-house-jamee.firebaseapp.com',
    storageBucket: 'coffee-house-jamee.firebasestorage.app',
  );
}
